[pytest]
asyncio_mode = auto
testpaths = tests
pythonpath = packages/netpi-core packages/netpi-analyzer packages/netpi-cabletester packages/netpi-discovery packages/netpi-dmx packages/netpi-server packages/netpi-tests packages/netpi-db packages/netpi-osc packages/netpi-oca
filterwarnings =
    ignore::DeprecationWarning:scapy.*
    ignore::DeprecationWarning:pkg_resources.*



