from abc import ABC, abstractmethod
from typing import Callable
from netpi_core.models.dmx import DMXPacket, DMXUniverse

class DMXBackend(ABC):
    name: str = "abstract"
    @abstractmethod
    async def open(self) -> bool: ...
    @abstractmethod
    async def close(self) -> None: ...
    @abstractmethod
    async def is_available(self) -> bool: ...
    @abstractmethod
    async def send_universe(self, universe: DMXUniverse) -> bool: ...
    @abstractmethod
    async def start_receiver(self, callback: Callable[[DMXPacket], None]) -> None: ...
    @abstractmethod
    async def stop_receiver(self) -> None: ...
    @abstractmethod
    async def send_rdm_discovery(self) -> list[str]: ...
    @abstractmethod
    async def send_rdm_get(self, uid: str, pid: int, sub_device: int = 0) -> bytes | None: ...
    @abstractmethod
    async def send_rdm_set(self, uid: str, pid: int, data: bytes, sub_device: int = 0) -> bool: ...
